
owner: SebaYB
repo: HaworthStatus

sites:
  - name: Haworth Landing Page
    url: https://haworth-rp.com
  - name: Haworth Foro
    url: https://foro.haworth-rp.com
  - name: Haworth Foro Law
    url: https://law.haworth-rp.com
  - name: Haworth Roleplay - v1.0.1
    url: https://samp.haworth-rp.com
    
assignees:
  - SebaYB
  
# Adicionales
user-agent: SebaYB

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  theme: dark
  baseUrl: /HaworthStatusPage
  logoUrl: https://media.discordapp.net/attachments/1069721282435883119/1072015861617012756/falklandstrazo.png?width=325&height=325
  favicon: https://media.discordapp.net/attachments/1069721282435883119/1069722844193366117/Sin_titulo-1.png?width=325&height=325
  name: Haworth Roleplay
  introTitle: "En **Haworth** Status podrás ver el estado de nuestros servidores."
  introMessage: Los estados se encuentran en **tiempo real**, puedes suscribirte al repositorio de GitHub para ser notificado al instante.
  navbar:
    - title: Haworth Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Discord
      href: https://discord.com/invite/haworth/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
